version: 2.1
executors:
  default:
    docker:
    - image: circleci/golang:1.16.2

aliases:
- &restore_cache
  restore_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
- &save_cache
  save_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
    paths:
      - "/go/pkg/mod"

jobs:
    check-boilerplate:
      executor:
        name: default
      steps:
      - checkout
      - run: ./scripts/verify-boilerplate.sh

    push-docker-pr:
        executor:
            name: default
        steps:
        - checkout
        - setup_remote_docker
        - run: make build-image
        - run: ./scripts/push-docker-pr.sh
        - run:
            name: Re-run Docker Push if fail
            command: |
                sleep 20
                ./scripts/push-docker-pr.sh
            when: on_fail

    push-docker:
        executor:
            name: default
        steps:
        - checkout
        - setup_remote_docker
        - run: make build-image
        - run: ./scripts/push-docker.sh
        - run:
            name: Re-run Docker Push if fail
            command: |
                sleep 20
                ./scripts/push-docker.sh
            when: on_fail

    test:
        - image: circleci/golang:1.16.2
          environment:
            AWAT_DATABASE=postgres://cloud_test@localhost:5432/cloud_test?sslmode=disable
        - image: circleci/postgres:11.2-alpine
        environment:
            POSTGRES_USER: cloud_test
            POSTGRES_DB: cloud_test
        executor:
          name: default
        steps:
          - checkout
          - run: make test

workflows:
  version: 2
  ci-build:
    jobs:
    - check-boilerplate
    - test
    - push-docker-pr
